
name: Create and publish a Docker image

on:
  repository_dispatch:
    types:
      - trigger
  
jobs:
  cnspec-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Install cnspec
      run: |
        bash -c "$(curl -sSL https://install.mondoo.com/sh)"
    - name: Scan Docker Image with cnspec
      run: |
        cnspec scan docker file Dockerfile --policy-bundle policies.yml --incognito --score-threshold 100
  generate-variable:
    runs-on: ubuntu-latest
    needs: cnspec-check
    outputs:
      download_url: ${{ steps.set-output.outputs.download_url }}
    steps:
      - name: Set download url
        id: set-output
        run: |
          download_url=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/joekl17/mondoo_phase1/releases/latest | jq -r '.assets[] | select(.name == "mondoo_phase1-'${{ github.event.client_payload.release_tag }}'-linux-amd64.tar.gz") | .url')
          echo "download_url=$download_url" >> $GITHUB_OUTPUT  
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: generate-variable
    env:
      DOWNLOAD_URL: ${{ needs.generate-variable.outputs.download_url }} 
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            TOKEN=${{ secrets.TOKEN }}
            DOWNLOAD_URL=${{ needs.generate-variable.outputs.download_url }} 
          push: true
          platforms: linux/amd64
          tags: ghcr.io/joekl17/mondoo_phase2:${{ github.event.client_payload.release_tag }}
